// @generated
// This file was automatically generated and should not be edited.
// Copyright ©, 2023-present, Lightspark Group, Inc. - All Rights Reserved
import Foundation

/// This object represents a request made for an L1 withdrawal from your Lightspark Node to any Bitcoin wallet. You can retrieve this object to receive detailed information about any withdrawal request made from your Lightspark account.
public struct WithdrawalRequest: Entity, Decodable {
    enum CodingKeys: String, CodingKey {

        case id = "withdrawal_request_id"

        case createdAt = "withdrawal_request_created_at"

        case updatedAt = "withdrawal_request_updated_at"

        case amount = "withdrawal_request_amount"

        case estimatedAmount = "withdrawal_request_estimated_amount"

        case bitcoinAddress = "withdrawal_request_bitcoin_address"

        case status = "withdrawal_request_status"

        case completedAt = "withdrawal_request_completed_at"

        case withdrawal = "withdrawal_request_withdrawal"

    }

    /// The unique identifier of this entity across all Lightspark systems. Should be treated as an opaque string.
    public var id: String

    /// The date and time when the entity was first created.
    public var createdAt: Date

    /// The date and time when the entity was last updated.
    public var updatedAt: Date

    /// The amount of money that should be withdrawn in this request.
    public var amount: CurrencyAmount

    /// If the requested amount is `-1` (i.e. everything), this field may contain an estimate of the amount for the withdrawal.
    public var estimatedAmount: CurrencyAmount?

    /// The bitcoin address where the funds should be sent.
    public var bitcoinAddress: String

    /// The current status of this withdrawal request.
    public var status: WithdrawalRequestStatus

    /// The time at which this request was completed.
    public var completedAt: Date?

    /// The withdrawal transaction that has been generated by this request.
    public var withdrawal: EntityWrapper?

}

extension WithdrawalRequest {
    public static let fragment = """

        fragment WithdrawalRequestFragment on WithdrawalRequest {
            __typename
            withdrawal_request_id: id
            withdrawal_request_created_at: created_at
            withdrawal_request_updated_at: updated_at
            withdrawal_request_amount: amount {
                __typename
                currency_amount_original_value: original_value
                currency_amount_original_unit: original_unit
                currency_amount_preferred_currency_unit: preferred_currency_unit
                currency_amount_preferred_currency_value_rounded: preferred_currency_value_rounded
                currency_amount_preferred_currency_value_approx: preferred_currency_value_approx
            }
            withdrawal_request_estimated_amount: estimated_amount {
                __typename
                currency_amount_original_value: original_value
                currency_amount_original_unit: original_unit
                currency_amount_preferred_currency_unit: preferred_currency_unit
                currency_amount_preferred_currency_value_rounded: preferred_currency_value_rounded
                currency_amount_preferred_currency_value_approx: preferred_currency_value_approx
            }
            withdrawal_request_bitcoin_address: bitcoin_address
            withdrawal_request_status: status
            withdrawal_request_completed_at: completed_at
            withdrawal_request_withdrawal: withdrawal {
                id
            }
        }
        """
}
